# Generated by Django 3.1.7 on 2021-04-29 18:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageProxyObject',
            fields=[
            ],
            options={
                'verbose_name': 'info page',
                'verbose_name_plural': 'info pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.CreateModel(
            name='UserProxyObject',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-pk'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
