# Generated by Django 3.1.7 on 2021-05-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_auto_20210502_1116'),
        ('teams', '0002_remove_team_num_unlock_points'),
    ]

    operations = [
#        migrations.CreateModel(
#            name='TeamHeadstartEpisode',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('time', models.DurationField(default='00', help_text='The headstart value for this team (HAS NO EFFECT YET)')),
#                ('episode', models.ForeignKey(help_text='The episode associated', on_delete=django.db.models.deletion.CASCADE, to='hunts.episode')),
#                ('team', models.ForeignKey(help_text='The team that this headstart is for', on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
#            ],
#            options={
#                'verbose_name_plural': 'Headstart gained by teams',
#                'unique_together': {('episode', 'team')},
#            },
#        ),
    ]
