language: python

services:
  - docker

sudo: required

env:
  global:
    - DB_USER=hunt
    - DB_PASSWORD=test
    - DJANGO_SECRET_KEY=test_secret_key
    - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose exec app coverage run
  - docker-compose exec app coverage report

after_script:
  - docker-compose stop
  - docker-compose rm -f

after_success:
  - pip install coveralls flake8
  - cp .coverage .coverage.extra
  - coverage combine
  - coveralls
  - flake8 huntserver