language: python

python:
  - "2.7"
services:
  - mysql
env:
  -DJANGO=1.8 DB=mysql
install:
  - pip install -r requirements.txt
  - mkdir -p ./media/puzzles
before_script:
  - mysql -e 'create database puzzlehunt_db;' -u root
script:
  - python manage.py test