version: '3'

services:
  db:
    image: ${DB_IMAGE}
    restart: always
    environment:
      # Bot sets of variables here for flexibility
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    restart: always
    command: gunicorn --workers=2 --bind=0.0.0.0:8000 puzzlehunt_server.wsgi:application
    volumes:
      - .:/code
      - static:/static
      - media:/media

    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_ENABLE_DEBUG
      - DJANGO_EMAIL_USER
      - DJANGO_EMAIL_PASSWORD
      - DJANGO_SETTINGS_MODULE=puzzlehunt_server.settings.env_settings
      - DATABASE_URL=${DB_TYPE}://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      - db

  web:
    restart: always
    container_name: web_server
    build:
      context: ./docker/
      dockerfile: nginxDockerfile
      # dockerfile: apacheDockerfile
    depends_on:
      - app
    volumes:
      - static:/static
      - media:/media
    ports:
      - "0.0.0.0:80:80"
    tty: true

volumes:
  static:
  media: