version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    restart: always
    volumes:
#      - .:/code  # Enables live modification of django files
      - static:/static
      - media:/media
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_ENABLE_DEBUG
      - DJANGO_EMAIL_USER
      - DJANGO_EMAIL_PASSWORD
      - DJANGO_USE_SHIBBOLETH
      - DJANGO_SETTINGS_MODULE=puzzlehunt_server.settings.env_settings
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      - db

  web:
    restart: always
    container_name: web_server
    build:
      context: ./docker/
      dockerfile: apacheDockerfile
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    depends_on:
      - app
    volumes:
      - static:/static
      - media:/media
    ports:
      - "0.0.0.0:80:80"
    environment:
      - DOMAIN
      - CONTACT_EMAIL
    tty: true

volumes:
  static:
  media: