version: '3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: puzzlehunt_db
      MYSQL_USER: hunt
      MYSQL_PASSWORD: sample_password
      MYSQL_ROOT_PASSWORD: test

  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: puzzlehunt_db
  #     POSTGRES_USER: hunt
  #     POSTGRES_PASSWORD: sample_password

  app:
    build:
      context: .
    restart: always
    command: gunicorn --workers=2 --bind=0.0.0.0:8000 puzzlehunt_server.wsgi:application
    volumes:
      - .:/code
      - static:/static
      - media:/media

    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_NAME: puzzlehunt_db
      DJANGO_DB_USER: hunt
      DJANGO_DB_PASSWORD: sample_password
      DJANGO_SECRET_KEY: somesecretkeythatisprobablylongerandbetterthanthis
      DJANGO_SETTINGS_MODULE: puzzlehunt_server.settings.env_settings
    depends_on:
      - db

  web:
    restart: always
    container_name: web_server
    build:
      context: ./docker/
      dockerfile: nginxDockerfile
      # dockerfile: apacheDockerfile
    depends_on:
      - app
    volumes:
      - static:/static
      - media:/media
    ports:
      - "0.0.0.0:80:80"
    tty: true

volumes:
  static:
  media: