version: '3'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: puzzlehunt_db
      MYSQL_USER: hunt
      MYSQL_PASSWORD: sample_password

  web:
    build: .
    restart: always
    command: gunicorn --workers=2 --bind=0.0.0.0:8000 puzzlehunt_server.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: puzzlehunt_db
      MYSQL_USER: hunt
      MYSQL_PASSWORD: sample_password
    depends_on:
      - db