# Generated by Django 3.1.7 on 2021-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepuzzle',
            name='template',
            field=models.TextField(default='{% extends "puzzle/prepuzzle.html" %}\r\n{% load prepuzzle_tags %}\r\n\r\n{% block content %}\r\n{% endblock content %}', help_text='The template string to be rendered to HTML on the hunt page'),
        ),
    ]
