# Generated by Django 3.1.7 on 2021-05-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_number',
            field=models.IntegerField(default=1, help_text='The number of the puzzle within the episode, for sorting purposes (must be unique within the episode, and not too large)'),
        ),
    ]
