# Generated by Django 3.1.7 on 2021-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_type',
            field=models.CharField(choices=[('SOL', 'Solves Based Unlock'), ('POT', 'Points Based Unlock'), ('ETH', 'Either (OR) Unlocking Method'), ('BTH', 'Both (AND) Unlocking Methods')], default='SOL', help_text='The type of puzzle unlocking scheme', max_length=3),
        ),
    ]
