# Generated by Django 3.1.7 on 2021-05-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_auto_20210501_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='points_per_minute',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='points_cost',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='points_value',
        ),
    ]
