# Generated by Django 3.1.7 on 2021-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0003_auto_20210502_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='ep_number',
            field=models.IntegerField(help_text='A number used internally for episode sorting, must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='start_date',
            field=models.DateTimeField(help_text='The date/time at which this episode will become visible to registered users (without headstarts)'),
        ),
    ]
