# Generated by Django 2.2.18 on 2021-04-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0072_auto_20201103_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Eureka',
        ),
        migrations.RenameModel(
            old_name='Solve',
            new_name='PuzzleSolve',
        ),
        migrations.RenameModel(
            old_name='Unlock',
            new_name='PuzzleUnlock',
        ),
        migrations.RemoveField(
            model_name='hintunlockplan',
            name='hunt',
        ),
        migrations.RemoveField(
            model_name='message',
            name='team',
        ),
        migrations.RemoveField(
            model_name='hunt',
            name='hint_lockout',
        ),
        migrations.RemoveField(
            model_name='hunt',
            name='location',
        ),
        migrations.RemoveField(
            model_name='person',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.RemoveField(
            model_name='team',
            name='num_available_hints',
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
        migrations.DeleteModel(
            name='HintUnlockPlan',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
