# Generated by Django 2.2.18 on 2021-04-04 18:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0073_auto_20210403_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text to display', max_length=400)),
                ('time', models.DurationField(help_text='Time after anyone on the team first loads the puzzle or (if set) unlocks the related eureka to display this hint', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Delay')),
                ('puzzle', models.ForeignKey(help_text='The puzzle that this automated response is related to', on_delete=django.db.models.deletion.CASCADE, to='huntserver.Puzzle')),
                ('start_after', models.ForeignKey(blank=True, help_text='If you select an eureka here, the time will start counting from when that is unlocked.', null=True, on_delete=django.db.models.deletion.CASCADE, to='huntserver.Eureka', verbose_name='Start after Eureka')),
            ],
        ),
        migrations.CreateModel(
            name='EurekaUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='The time this puzzle was unlocked for this team')),
                ('eureka', models.ForeignKey(help_text='The eureka unlocked', on_delete=django.db.models.deletion.CASCADE, to='huntserver.Eureka')),
                ('team', models.ForeignKey(help_text='The team that this unlocked puzzle is for', on_delete=django.db.models.deletion.CASCADE, to='huntserver.Team')),
            ],
            options={
                'unique_together': {('eureka', 'team')},
            },
        ),
    ]
