# Generated by Django 2.2.18 on 2021-04-04 21:37

import datetime
import django.core.validators
from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0074_eurekaunlock_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='start_after',
        ),
        migrations.AddField(
            model_name='hint',
            name='eurekas',
            field=models.ManyToManyField(blank=True, help_text='Eurekas that are a prerequisite for shorter time', to='huntserver.Eureka', verbose_name='Eureka conditions'),
        ),
        migrations.AddField(
            model_name='hint',
            name='short_time',
            field=models.DurationField(default=timedelta(), help_text='Time after anyone on the team first loads the puzzle', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Delay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hint',
            name='time',
            field=models.DurationField(help_text='Time after anyone on the team first loads the puzzle', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Delay'),
        ),
    ]
