# Generated by Django 2.2.18 on 2021-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0076_auto_20210405_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='location',
        ),
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, help_text='The country the members of the team are from', max_length=80),
        ),
    ]
