# Generated by Django 2.2.18 on 2021-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0077_auto_20210405_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_id',
            field=models.CharField(help_text='A 3-12 character hex string that uniquely identifies the puzzle', max_length=12, unique=True),
        ),
    ]
