# Generated by Django 3.1.7 on 2021-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0078_auto_20210405_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, help_text='The country the members of the team are from', max_length=80, null=True),
        ),
    ]
