# Generated by Django 3.1.7 on 2021-04-27 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huntserver', '0079_auto_20210406_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_name', models.CharField(help_text='The name of the episode as the public will see it', max_length=200)),
                ('ep_number', models.IntegerField(help_text='A number used internally for hunt sorting, must be unique', unique=True)),
                ('start_date', models.DateTimeField(help_text='The date/time at which a hunt will become visible to registered users')),
                ('hunt', models.ForeignKey(help_text='The hunt that this episode is a part of', on_delete=django.db.models.deletion.CASCADE, to='huntserver.hunt')),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_time', models.DateTimeField()),
                ('guess_text', models.CharField(max_length=100)),
                ('response_text', models.CharField(blank=True, help_text='Response to the given answer. Empty string indicates human response needed', max_length=400)),
                ('modified_date', models.DateTimeField(help_text='Last date/time of response modification')),
            ],
            options={
                'verbose_name_plural': 'Guesses',
            },
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['-episode', 'puzzle_number']},
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hunt',
        ),
        migrations.RemoveField(
            model_name='puzzlesolve',
            name='submission',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='template',
            field=models.TextField(default='', help_text='The template string to be rendered to HTML on the puzzle page'),
        ),
        migrations.AddField(
            model_name='team',
            name='eurekas',
            field=models.ManyToManyField(blank=True, help_text='The eurekas the team has unlocked', related_name='eurekas_for', through='huntserver.EurekaUnlock', to='huntserver.Eureka'),
        ),
        migrations.AlterField(
            model_name='eureka',
            name='answer',
            field=models.CharField(help_text='The text to use in the guess response if the regex matched', max_length=400),
        ),
        migrations.AlterField(
            model_name='eurekaunlock',
            name='time',
            field=models.DateTimeField(help_text='The time this eureka was unlocked for this team'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_number',
            field=models.IntegerField(help_text='The number of the puzzle within the episode, for sorting purposes'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='guess',
            name='puzzle',
            field=models.ForeignKey(help_text='The puzzle that this guess is in response to', on_delete=django.db.models.deletion.CASCADE, to='huntserver.puzzle'),
        ),
        migrations.AddField(
            model_name='guess',
            name='team',
            field=models.ForeignKey(help_text='The team that made the guess', on_delete=django.db.models.deletion.CASCADE, to='huntserver.team'),
        ),
        migrations.AddField(
            model_name='guess',
            name='user',
            field=models.ForeignKey(help_text='The user that made the guess', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='episode',
            field=models.ForeignKey(default=1, help_text='The episode that this puzzle is a part of', on_delete=django.db.models.deletion.CASCADE, to='huntserver.episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzlesolve',
            name='guess',
            field=models.ForeignKey(blank=True, default=0, help_text='The guess object that the team submitted to solve the puzzle', on_delete=django.db.models.deletion.CASCADE, to='huntserver.guess'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['ep_number'], name='huntserver__ep_numb_9ebd7d_idx'),
        ),
    ]
