# Generated by Django 3.1.7 on 2021-04-08 08:43

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion

def create_episode(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Episode = apps.get_model("huntserver", "Episode")
    Hunt = apps.get_model("huntserver", "Hunt")
    Episode.objects.using(db_alias).create(hunt=Hunt.objects.get(is_current_hunt=True), ep_name="Ep test", ep_number="1", start_date=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0079_auto_20210406_0345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['-episode', 'puzzle_number']},
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hunt',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_name', models.CharField(help_text='The name of the episode as the public will see it', max_length=200)),
                ('ep_number', models.IntegerField(help_text='A number used internally for hunt sorting, must be unique', unique=True)),
                ('start_date', models.DateTimeField(help_text='The date/time at which a hunt will become visible to registered users')),
                ('hunt', models.ForeignKey(help_text='The hunt that this episode is a part of', on_delete=django.db.models.deletion.CASCADE, to='huntserver.hunt')),
            ],
        ),
        migrations.RunPython(create_episode),
        migrations.AddField(
            model_name='puzzle',
            name='episode',
            field=models.ForeignKey(default=1, help_text='The episode that this puzzle is a part of', on_delete=django.db.models.deletion.CASCADE, to='huntserver.episode'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['ep_number'], name='huntserver__ep_numb_9ebd7d_idx'),
        ),
    ]
