# Generated by Django 3.1.7 on 2021-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0080_auto_20210408_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='template',
            field=models.TextField(default='', help_text='The template string to be rendered to HTML on the puzzle page'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_number',
            field=models.IntegerField(help_text='The number of the puzzle within the episode, for sorting purposes'),
        ),
    ]
