# Generated by Django 3.1.7 on 2021-04-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0081_auto_20210408_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_time', models.DateTimeField()),
                ('guess_text', models.CharField(max_length=100)),
                ('response_text', models.CharField(blank=True, help_text='Response to the given answer. Empty string indicates human response needed', max_length=400)),
                ('modified_date', models.DateTimeField(help_text='Last date/time of response modification')),
                ('puzzle', models.ForeignKey(help_text='The puzzle that this guess is in response to', on_delete=django.db.models.deletion.CASCADE, to='huntserver.puzzle')),
                ('team', models.ForeignKey(help_text='The team that made the guess', on_delete=django.db.models.deletion.CASCADE, to='huntserver.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzlesolve',
            name='submission',
        ),
        migrations.AlterField(
            model_name='eureka',
            name='answer',
            field=models.CharField(help_text='The text to use in the guess response if the regex matched', max_length=400),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='puzzlesolve',
            name='guess',
            field=models.ForeignKey(blank=True, default=1, help_text='The guess object that the team submitted to solve the puzzle', on_delete=django.db.models.deletion.CASCADE, to='huntserver.guess'),
            preserve_default=False,
        ),
    ]
