# Generated by Django 3.1.7 on 2021-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0083_auto_20210409_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='eurekas',
            field=models.ManyToManyField(blank=True, help_text='The eurekas the team has unlocked', related_name='eurekas_for', through='huntserver.EurekaUnlock', to='huntserver.Eureka'),
        ),
        migrations.AlterField(
            model_name='eurekaunlock',
            name='time',
            field=models.DateTimeField(help_text='The time this eureka was unlocked for this team'),
        ),
    ]
